apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-credentials
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  # Valeur encodée en base64 de :
  # {"auths":{"https://index.docker.io/v1/":{"username":"den95","password":"<DOCKER_PASSWORD>","auth":"<base64(username:password)>"}}}
  # Remplacer par : kubectl create secret docker-registry dockerhub-credentials \
  #   --docker-username=den95 --docker-password=<TOKEN> \
  #   --docker-server=https://index.docker.io/v1/ -n default
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnt9fX0=
